// Eduardo Aguilera
// CS145
// Demonstrate understanding of abstract class
// Either going to reuse code from Polymorphism assignment or revise it into Pokemon

public class Assignment5 {
    public static void main(String[] args) {
        // maybe create menu to select pokemon that the user wants to throw a pokeball at
        System.out.println("You caught a Cubone Pokemon!");
        System.out.println("What would you like to name it?")
        // user input, reuse code from previous assingment with try catch
        // create array of Pokemon the user has caught? or would that be too much
        // or create just a singular variable that stores users caught pokemon and user can then
        // make the selected pokemon do an action
    }
}